version: '3.7'

services:
  db:
    image: mariadb:latest
    container_name: db_apexvigne
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_apexvigne
    restart: always
    environment:
      UPLOAD_LIMIT: 30M
    env_file: .env
    ports:
      - "8080:80"
    depends_on:
      - db

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app_apexvigne
    env_file: .env
    ports:
      - "80:5000"
    depends_on:
      - db
    links:
      - db
      